#!/bin/bash
##########################################################################################
# By Diego Cardenas "The Samedog" under GNU GENERAL PUBLIC LICENSE Version 2, June 1991
# (www.gnu.org/licenses/old-licenses/gpl-2.0.html) e-mail: the.samedog[]gmail.com.
# https://github.com/samedog/frankenpup64
##########################################################################################
# This should work on ANY distro with xrandr regardless or video driver
# (thanks to hugecomputerdisaster)
# it's a non-auto night mode switch because **WHY ON EARTH** should i use a
# fucking gps location to change the screen gamma, Jesus fucking Christ on a pogo stick
##########################################################################################

if [ ! -f /tmp/day.l ];then
	echo "1" > /tmp/day.l
fi
BACKL_NAME=$(ls /sys/class/backlight/ | tr "\n" " ")
arr_list=($BACKL_NAME)


##simple percentage calcualtion for easy brightness handling
function b_percentage(){
	RET=$(expr $1 \* $2 / 100)
}

##brightness/gamma switch function 
function switch() {
	DAY_L=$(head -1 /tmp/day.l)
	for val in "$@"
		do
			if [ $DAY_L -eq 0 ];then
				xrandr --output "$val" --gamma 1:1:1 --brightness 1
				echo "Setting: xrandr --output $val --gamma 1:1:1 --brightness 1"
				if [ -f "$BACKL_DEVICE" ];then
					echo $MAX_B > $BACKL_DEVICE
				fi
				echo "1" > /tmp/day.l
			else
				xrandr --output "$val" --gamma 1:0.8:0.5 --brightness 0.5
				echo "Setting: xrandr --output $val --gamma 1:0.8:0.5 --brightness 0.5"
				if [ -f "$BACKL_DEVICE" ];then
					b_percentage $MAX_B 50
					echo $RET > $BACKL_DEVICE
				fi
				echo "0" > /tmp/day.l
			fi
		done
}

## we call the switch function into the loop
function call_switch(){
		BACKL_DEVICE="/sys/class/backlight/$1/brightness"
		MAX_B=$(cat /sys/class/backlight/$BACKL_NAME/max_brightness)
		SCREENS=$(xrandr | grep "$DISPLAY1 connected" | cut -d' ' -f1)
		switch "$SCREENS"
}


##we set ALL the found backlight controllers brightness,
##this way we ensure even monitors attached on runtime will change too
if [ ${#arr_list[@]} -gt 1 ];then
	for ((i=0;i<${#arr_list[@]};i++))
	do
		BACKL_NAME=${arr_list[$i]}
		call_switch $BACKL_NAME
	done
else
	BACKL_NAME=${arr_list[0]}
	call_switch $BACKL_NAME
fi
