#!/bin/bash
##########################################################################################
# By Diego Cardenas "The Samedog" under GNU GENERAL PUBLIC LICENSE Version 2, June 1991
# (www.gnu.org/licenses/old-licenses/gpl-2.0.html) e-mail: the.samedog[]gmail.com.
# https://github.com/samedog/frankenpup64
##########################################################################################
# This should work on ANY distro with xrandr regardless or video driver
# (thanks to hugecomputerdisaster)
# it's a non-auto night mode switch because **WHY ON EARTH** should i use a
# fucking gps location to change the screen gamma, Jesus fucking Christ on a pogo stick
# 18-11-2019: - First release
#
##########################################################################################

if [ ! -f /tmp/day.l ];then
	echo "1" > /tmp/day.l
fi

SCREENS=$(xrandr | grep "$DISPLAY1 connected" | cut -d' ' -f1)

function switch() {
	DAY_L=$(head -1 /tmp/day.l)
	for val in "$@"
		do
			if [ $DAY_L -eq 0 ];then
				xrandr --output "$val" --gamma 1:1:1 --brightness 1
				echo "Setting: xrandr --output $val --gamma 1:1:1 --brightness 1"
				echo "1" > /tmp/day.l
			else
				xrandr --output "$val" --gamma 1:0.8:0.5 --brightness 0.5
				echo "Setting: xrandr --output $val --gamma 1:0.8:0.5 --brightness 0.5"
				echo "0" > /tmp/day.l
			fi
		done
}

switch "$SCREENS"


